/**
 * PALETTE GENERATED BY http://mcg.mbitson.com/ BTW
 */

import { Color } from '@material-ui/core';

export const AlteningGreen: Color = {
    '50': '#e6f4f2',
    '100': '#c0e4dd',
    '200': '#96d2c7',
    '300': '#6bbfb1',
    '400': '#4cb2a0',
    '500': '#2ca48f',
    '600': '#279c87',
    '700': '#21927c',
    '800': '#1b8972',
    '900': '#107860',
    A100: '#acffea',
    A200: '#79ffdd',
    A400: '#46ffd0',
    A700: '#2cffc9'
};
